FROM alpine:3.22
RUN apk add --no-cache apache2 apache2-proxy apache2-ssl
RUN mkdir -p /run/apache2 /etc/apache2/conf.d
RUN sed -i "s|#LoadModule proxy_module|LoadModule proxy_module|" /etc/apache2/httpd.conf; \
    sed -i "s|#LoadModule proxy_http_module|LoadModule proxy_http_module|" /etc/apache2/httpd.conf; \
    sed -i "s|#LoadModule rewrite_module|LoadModule rewrite_module|" /etc/apache2/httpd.conf
EXPOSE 80 443
CMD ["httpd", "-D", "FOREGROUND"]
