ServerName localhost
DocumentRoot /usr/local/apache2/htdocs
DirectoryIndex login.html

<Directory /usr/local/apache2/htdocs>
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>
